export const images = [
  {
    src: "/images/taide/kaikki-mita-mukanani-kannan.webp",
    alt: "Kaikki mitä mukanani kannan, 2026",
    title: "Kaikki mitä mukanani kannan, 2026",
    koko: "50 x 70 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/kukkivahuntu.webp",
    alt: "Kukkiva huntu, 2026",
    title: "Kukkiva huntu, 2026",
    koko: "40 x 50 cm",
    tekniikka: "Öljyväri, muste, akryyli mdf-levylle",
  },
  {
    src: "/images/taide/valkoinen-virta.webp",
    alt: "Valkoinen virta, 2025",
    title: "Valkoinen virta, 2025",
    koko: "50 x 61 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/voodoo-viidakkoseremonia.webp",
    alt: "Voodoo Viidakkoseremonia, 2025",
    title: "Voodoo Viidakkoseremonia, 2025",
    koko: "50 x 61 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/hetken-syleily.webp",
    alt: "Hetken syleily, 2026",
    title: "Hetken syleily, 2026",
    koko: "30 x 30 cm",
    tekniikka: "Akryyli mdf-levylle",
  },

  {
    src: "/images/taide/elavaksi-syntynyt.webp",
    alt: "Eläväksi syntynyt, 2026",
    title: "Eläväksi syntynyt, 2026",
    koko: "60 x 40 cm",
    tekniikka: "Akryyli ja muste kankaalle",
  },
  {
    src: "/images/taide/pataassa.webp",
    alt: "Pataässä",
    title: "Pataässä",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/kukkivatpaat.webp",
    alt: "Kukkivat päät, 2026",
    title: "Kukkivat päät, 2026",
    koko: "",
    tekniikka: "Akryyli mdf-levylle",
  },
  {
    src: "/images/taide/nayn-omainen.webp",
    alt: "Näyn omainen, 2024",
    title: "Näyn omainen, 2024",
    koko: "40 x 40 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/kuumakaaro.webp",
    alt: "Kuuma käärö, 2024",
    title: "Kuuma käärö, 2024",
    koko: "",
    tekniikka: "Akryyli mdf-levylle",
  },
  {
    src: "/images/taide/kukanimijat.webp",
    alt: "Kukanimijät, 2026",
    title: "Kukanimijät, 2026",
    koko: "46 x 38 cm",
    tekniikka: "Muste ja akryyli mdf-levylle",
  },
  {
    src: "/images/taide/imetys.webp",
    alt: "Syli, 2026",
    title: "Syli, 2026",
    koko: "",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/Taivaanmerkit.webp",
    alt: "Taivaan merkit, 2026",
    title: "Taivaan merkit, 2026",
    koko: "",
    tekniikka: "Akryyli mdf-levylle",
  },
  {
    src: "/images/taide/kuohuissani2.webp",
    alt: "Kuohuissani, 2026",
    title: "Kuohuissani, 2026",
    koko: "70 x 50 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/mieleni-tulva.webp",
    alt: "Mieleni tulva, 2026",
    title: "Mieleni tulva, 2026",
    koko: "50 x 61 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/meren-verkossa2.webp",
    alt: "Meren verkossa",
    title: "Meren verkossa",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/merenrannalla2.webp",
    alt: "Merenrannalla",
    title: "Merenrannalla",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/vuoristo.webp",
    alt: "Vuoret",
    title: "Vuoret",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/munankuoret/kannatteluja.webp",
    alt: "Kannatteluja, 2022",
    title: "Kannatteluja, 2022",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/luonto-luojan-suo.webp",
    alt: "Luonto Luojan suo, 2024",
    title: "Luonto Luojan suo, 2024",
    koko: "30 x 40 cm",
    tekniikka: "Puukaiverrus, munankuoret, akryyli puulevylle",
  },
  {
    src: "/images/taide/keraaminen-vanhus.webp",
    alt: "Keraaminen vanhus",
    title: "Keraaminen vanhus",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/munankuoret/liekki.webp",
    alt: "Sulamispiste, 2022",
    title: "Sulamispiste, 2022",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kirjontapohjalle",
  },
  {
    src: "/images/taide/munankuoret/maniac.webp",
    alt: "Maniac, 2021",
    title: "Maniac, 2021",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/munankuoret/napanuora.webp",
    alt: "Napanuora, 2021",
    title: "Napanuora, 2021",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/munankuoret/croissantti.webp",
    alt: "Croissantti puussa",
    title: "Croissantti puussa",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },

  {
    src: "/images/taide/wastingtime.webp",
    alt: "Wasting Time",
    title: "Wasting Time",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/munankuoret/pyha-akka.webp",
    alt: "Rukous, 2024",
    title: "Rukous, 2024",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kirjontapohjalle",
  },

  {
    src: "/images/taide/Tanssija.webp",
    alt: "Tanssija",
    title: "Tanssija",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/paperimosaiikkinukke.webp",
    alt: "Paperimosaiikkinukke",
    title: "Paperimosaiikkinukke",
    koko: "",
    tekniikka: "Lehtileikkeet paperille",
  },
  {
    src: "/images/taide/koristemaalaus1.webp",
    alt: "Koristemaalaus 1",
    title: "Koristemaalaus 1",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/3d.webp",
    alt: "Lohikäärme",
    title: "Lohikäärme",
    koko: "",
    tekniikka: "Gravity Sketch VR-hahmo",
  },
];
