export const images = [
  {
    src: "/images/taide/kaikkimitamukananikannan.webp",
    alt: "Kaikki mitä mukanani kannan, 2026",
    title: "Kaikki mitä mukanani kannan, 2026",
    koko: "50 x 70 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/Kukkiva-huntu.webp",
    alt: "Kukkiva huntu, 2026",
    title: "Kukkiva huntu, 2026",
    koko: "40 x 50 cm",
    tekniikka: "Öljyväri, muste, akryyli mdf-levylle",
  },
  {
    src: "/images/taide/Valkoinenvirta.webp",
    alt: "Valkoinen virta, 2025",
    title: "Valkoinen virta, 2025",
    koko: "50 x 61 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/Voodooviidakkoseremonia.webp",
    alt: "Voodoo Viidakkoseremonia, 2025",
    title: "Voodoo Viidakkoseremonia, 2025",
    koko: "50 x 61 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/hetken-syleily.webp",
    alt: "Hetken syleily, 2026",
    title: "Hetken syleily, 2026",
    koko: "30 x 30 cm",
    tekniikka: "Akryyli mdf-levylle",
  },

  {
    src: "/images/taide/Elavaksisyntynyt.webp",
    alt: "Eläväksi syntynyt, 2026",
    title: "Eläväksi syntynyt, 2026",
    koko: "60 x 40 cm",
    tekniikka: "Akryyli ja muste kankaalle",
  },
  {
    src: "/images/taide/pataassa.webp",
    alt: "Pataässä",
    title: "Pataässä",
    koko: "80 x 100 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/kukan-imijat.webp",
    alt: "Kukanimijät, 2026",
    title: "Kukanimijät, 2026",
    koko: "46 x 38 cm",
    tekniikka: "Muste ja akryyli mdf-levylle",
  },
  {
    src: "/images/taide/imetyssyli.webp",
    alt: "Syli, 2026",
    title: "Syli, 2026",
    koko: "",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/kukkivat-paat.webp",
    alt: "Kukkivat päät, 2026",
    title: "Kukkivat päät, 2026",
    koko: "",
    tekniikka: "Akryyli mdf-levylle",
  },
  {
    src: "/images/taide/Naynomainen.webp",
    alt: "Näyn omainen, 2024",
    title: "Näyn omainen, 2024",
    koko: "40 x 40 cm",
    tekniikka: "Akryyli kankaalle",
  },

  {
    src: "/images/taide/Taivaan-merkit.webp",
    alt: "Taivaan merkit, 2026",
    title: "Taivaan merkit, 2026",
    koko: "",
    tekniikka: "Akryyli mdf-levylle",
  },
  {
    src: "/images/taide/kuohuksissa.webp",
    alt: "Kuohuissani, 2026",
    title: "Kuohuissani, 2026",
    koko: "70 x 50 cm",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/metsa-ssa.webp",
    alt: "Metsässä, 2025",
    title: "Metsässä, 2025",
    koko: "",
    tekniikka: "Akryyli kankaalle",
  },
  {
    src: "/images/taide/mielenitulva.webp",
    alt: "Mieleni tulva, 2026",
    title: "Mieleni tulva, 2026",
    koko: "50 x 61 cm",
    tekniikka: "Akryyli kankaalle",
  },

  {
    src: "/images/taide/meren-verkossa2.webp",
    alt: "Meren verkossa",
    title: "Meren verkossa",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/merenrannalla2.webp",
    alt: "Merenrannalla",
    title: "Merenrannalla",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/vuoristo.webp",
    alt: "Vuoret",
    title: "Vuoret",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/munankuoret/Mustaiso.webp",
    alt: "Kannatteluja, 2022",
    title: "Kannatteluja, 2022",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/munankuoret/Luonto-luoja-suo.webp",
    alt: "Luonto Luojan suo, 2024",
    title: "Luonto Luojan suo, 2024",
    koko: "30 x 40 cm",
    tekniikka: "Puukaiverrus, munankuoret, akryyli puulevylle",
  },
  {
    src: "/images/taide/keraaminen-vanhus.webp",
    alt: "Keraaminen vanhus",
    title: "Keraaminen vanhus",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/munankuoret/Sulamistpiste.webp",
    alt: "Sulamispiste, 2022",
    title: "Sulamispiste, 2022",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kirjontapohjalle",
  },
  {
    src: "/images/taide/mania.webp",
    alt: "Maniac, 2021",
    title: "Maniac, 2021",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/munankuoret/napanuora.webp",
    alt: "Napanuora, 2021",
    title: "Napanuora, 2021",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/munankuoret/croissantti.webp",
    alt: "Croissantti puussa",
    title: "Croissantti puussa",
    koko: "50 x 40 cm",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },

  {
    src: "/images/taide/wastingtime1.webp",
    alt: "Wasting Time",
    title: "Wasting Time",
    koko: "",
    tekniikka: "",
  },
  {
    src: "/images/taide/munankuoret/pyha-akka.webp",
    alt: "Rukous, 2024",
    title: "Rukous, 2024",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kirjontapohjalle",
  },
  {
    src: "/images/taide/munankuoret/Luonnollistako.webp",
    alt: "Luonnollistako, 2022",
    title: "Luonnollistako, 2022",
    koko: "",
    tekniikka: "Akryyli ja munankuoret pahville",
  },

  {
    src: "/images/taide/tanssija.webp",
    alt: "Tanssija",
    title: "Tanssija",
    koko: "",
    tekniikka: "Akryyli ja munankuoret kankaalle",
  },
  {
    src: "/images/taide/paperimosaiikkinukke.webp",
    alt: "Paperimosaiikkinukke",
    title: "Paperimosaiikkinukke",
    koko: "",
    tekniikka: "Lehtileikkeet paperille",
  },
  {
    src: "/images/taide/3d.webp",
    alt: "Lohikäärme",
    title: "Lohikäärme",
    koko: "",
    tekniikka: "Gravity Sketch VR-hahmo",
  },
];
